### PR TITLE
Feature/stagg mg

### PR DESCRIPTION
**Pull request by weinbe2**
This PR addresses a stray `}` that accidentally found its way into the first PR. It also replaced the `CTIME =` with `CTIME ?=` to streamline overriding `CTIME` from the command line.

### CODE REVIEW

**Comment by weinbe2** [comment]
@detar FYI on some MG-specific bugfix changes here. This should be a clean merge otherwise.

**Comment by weinbe2** [comment]
@detar what's the status of you merging this into `develop`?

**Comment by weinbe2** [comment]
Or at least into the `feature/staggMG` branch in the MILC repo as opposed to my own?

**Comment by detar** [comment]
Hi Evan,

I am not super fluent in git.  The original PR pointed to an incorrect 
branch of milc-qcd.  I merged those changes by hand at that time, and 
you have been using them.  So that PR was still posted on the milc-qcd 
repo, but I thought it was stale.  Your question suggests not.  What is 
its current status?

I haven't touched feature/staggMG for a couple weeks.  If your PR is 
still open and needed, I guess I should merge it with the 
feature/staggMG branch, then merge develop into feature/staggMG to 
resolve any conflicts, and finally, merge the result into develop, so we 
can close the feature/staggMG branch and work from develop from now on.

Best,

Carleton

**Comment by weinbe2** [comment]
That PR was stale and I believe I got rid of it, this is a new PR.

I remember the difficulties you went through last time, so I checked carefully that this PR is merging into the milc-qcd repo's `feature/staggMG` branch and not directly into `develop`. I can make some time today to merge `develop` into my branch so it'll be a clean one-two effort for you to merge this branch directly into MILC develop.

**Comment by detar** [comment]
I went ahead and merged the PR.  I'll reconcile milc-qcd:develop with milc-qcd:feature/staggMG next.

**Comment by weinbe2** [comment]
Thank you Carleton, yesterday got away from me.

**Pull request merged**
